setTimeout(()=>{document.querySelectorAll('#form input[type="number"]').forEach(input=>input.step='any');document.querySelector('#form').addEventListener('submit',()=>{const speed=Number(document.querySelector('#wind-speed').value);document.querySelector('#wind').textContent=`${['북','북동','동','남동','남','남서','서','북서'][Math.round((Number(document.querySelector('#wind-dir').value)||0)/45)%8]}풍 ${speed.toFixed(2)}m/s`;});},0);
let landFeatures=[];fetch('data/land.geojson').then(r=>r.json()).then(d=>landFeatures=d.features||[]);
function inRing(p,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j],hit=((a[1]>p.lat)!=(b[1]>p.lat))&&p.lng<(b[0]-a[0])*(p.lat-a[1])/(b[1]-a[1])+a[0];if(hit)inside=!inside}return inside}
function landAt(p){return landFeatures.some(f=>{const g=f.geometry;if(g.type==='Polygon')return inRing(p,g.coordinates[0]);if(g.type==='MultiPolygon')return g.coordinates.some(x=>inRing(p,x[0]));return false})}
const basePolyline=L.polyline;L.polyline=(points,options)=>basePolyline(window.seaekRoute?.length>1?window.seaekRoute:points,options);
const origin=[35.1587,129.1604];let chosen={lat:origin[0],lng:origin[1]};const tiles='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
const map=L.map('input-map').setView(origin,13);L.tileLayer(tiles,{attribution:'&copy; OpenStreetMap'}).addTo(map);const pin=L.marker(origin,{draggable:true}).addTo(map);
function setLocation(p){chosen={lat:p.lat,lng:p.lng};pin.setLatLng(p);document.querySelector('#location').textContent=`선택 위치: 위도 ${p.lat.toFixed(5)}, 경도 ${p.lng.toFixed(5)}`};map.on('click',e=>setLocation(e.latlng));pin.on('dragend',e=>setLocation(e.target.getLatLng()));
document.querySelector('#time').value=new Date().toISOString().slice(0,16);const form=document.querySelector('#form');form.insertAdjacentHTML('beforeend','<fieldset><legend>현재 바다 환경 직접 입력</legend><div class="grid"><label>풍향 (°)<input id="wind-dir" type="number" min="0" max="360" value="230"></label><label>풍속 (m/s)<input id="wind-speed" type="number" min="0" step="0.1" value="4"></label><label>해류 방향 (°)<input id="current-dir" type="number" min="0" max="360" value="90"></label><label>해류 속도 (km/h)<input id="current-speed" type="number" min="0" step="0.1" value="0.5"></label><label>파향 (°)<input id="wave-dir" type="number" min="0" max="360" value="230"></label><label>파고 (m)<input id="wave-height" type="number" min="0" step="0.1" value="0.5"></label></div><button type="button" id="live">현재 값 자동 입력</button><small>출처: Open‑Meteo 현재 기상·해양 모델</small></fieldset>');
const direction=d=>['북','북동','동','남동','남','남서','서','북서'][Math.round((Number(d)||0)/45)%8],value=id=>Number(document.querySelector(id).value)||0,vector=(d,s)=>({x:Math.sin(d*Math.PI/180)*s,y:Math.cos(d*Math.PI/180)*s});
function destination(lat,lng,d,km){const r=Math.PI/180,a=km/6371,b=d*r,p=lat*r,l=lng*r,p2=Math.asin(Math.sin(p)*Math.cos(a)+Math.cos(p)*Math.sin(a)*Math.cos(b));const end=[p2/r,(l+Math.atan2(Math.sin(b)*Math.sin(a)*Math.cos(p),Math.cos(a)-Math.sin(p)*Math.sin(p2)))/r],route=[[lat,lng]];let safe=[lat,lng];for(let i=1;i<=100;i+=1){const t=i/100,next={lat:lat+(end[0]-lat)*t,lng:lng+(end[1]-lng)*t};if(landFeatures.length&&landAt(next))break;safe=[next.lat,next.lng];route.push(safe)}window.seaekRoute=route;return safe}
document.querySelector('#live').addEventListener('click',async()=>{const button=document.querySelector('#live');button.textContent='현재 값 불러오는 중';try{const w=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${chosen.lat}&longitude=${chosen.lng}&current=wind_speed_10m,wind_direction_10m&wind_speed_unit=ms`),m=await fetch(`https://marine-api.open-meteo.com/v1/marine?latitude=${chosen.lat}&longitude=${chosen.lng}&current=wave_height,wave_direction,ocean_current_velocity,ocean_current_direction`);const weather=(await w.json()).current,sea=(await m.json()).current;document.querySelector('#wind-dir').value=weather.wind_direction_10m;document.querySelector('#wind-speed').value=weather.wind_speed_10m;document.querySelector('#current-dir').value=sea.ocean_current_direction;document.querySelector('#current-speed').value=sea.ocean_current_velocity;document.querySelector('#wave-dir').value=sea.wave_direction;document.querySelector('#wave-height').value=sea.wave_height;button.textContent='현재 값 자동 입력 완료'}catch{button.textContent='자동 입력 실패'}});
form.addEventListener('submit',e=>{e.preventDefault();const result=document.querySelector('#result');result.hidden=false;if(document.querySelector('#floating').value==='no'){document.querySelector('#summary').textContent='가라앉는 물체는 바다 표면 표류 예측 대상이 아닙니다. 마지막 위치 주변 해저 수색이 필요합니다.';return}const mass=value('#weight'),hours=Math.max(1,Math.min(24,(Date.now()-new Date(document.querySelector('#time').value))/36e5)),resist=1/(1+mass*.25),wd=value('#wind-dir'),ws=value('#wind-speed'),cd=value('#current-dir'),cs=value('#current-speed'),pd=value('#wave-dir'),ph=value('#wave-height'),a=vector(cd,cs*(.6+.4*resist)),b=vector((wd+180)%360,ws*3.6*.055*resist),c=vector((pd+180)%360,ph*.32*resist),sum={x:a.x+b.x+c.x,y:a.y+b.y+c.y},heading=(Math.atan2(sum.x,sum.y)*180/Math.PI+360)%360,km=Math.max(.05,Math.min(20,Math.hypot(sum.x,sum.y)*hours)),end=destination(chosen.lat,chosen.lng,heading,km),radius=Math.min(3,.25+ph*.35+ws*.035+hours*.025),prob=Math.max(35,Math.round(88-ph*10-ws*1.2-hours*.7));document.querySelector('#summary').textContent=`입력한 바람·해류·파도 값을 분석한 결과, ${direction(heading)}쪽 약 ${km.toFixed(2)}km 지점이 예상 중심 위치입니다. 반경 ${radius.toFixed(2)}km 안에 있을 확률은 약 ${prob}%입니다.`;document.querySelector('#wind').textContent=`${direction(wd)}풍 ${ws.toFixed(1)}m/s`;document.querySelector('#current').textContent=`${direction(cd)}쪽 ${cs.toFixed(1)}km/h`;document.querySelector('#wave').textContent=`${direction(pd)}쪽 파도 ${ph.toFixed(1)}m`;if(window.resultMap)window.resultMap.remove();window.resultMap=L.map('result-map').setView(end,13);L.tileLayer(tiles,{attribution:'&copy; OpenStreetMap'}).addTo(window.resultMap);L.polyline([[chosen.lat,chosen.lng],end],{color:'#087fae',weight:5,dashArray:'8 9'}).addTo(window.resultMap);L.circle(end,{radius:radius*1000,color:'#e76f51',fillOpacity:.2}).addTo(window.resultMap);L.marker(end).addTo(window.resultMap).bindPopup(`예상 위치 · ${prob}%`).openPopup();window.resultMap.fitBounds([[chosen.lat,chosen.lng],end],{padding:[30,30]})});
