const start = [35.1587, 129.1604]; let point = {lat:start[0],lng:start[1]};
const inputMap=L.map('input-map').setView(start,13), tiles='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
L.tileLayer(tiles,{attribution:'&copy; OpenStreetMap'}).addTo(inputMap); const marker=L.marker(start,{draggable:true}).addTo(inputMap);
function setPoint(p){point={lat:p.lat,lng:p.lng};marker.setLatLng(p);document.querySelector('#location').textContent=`선택 위치: 위도 ${p.lat.toFixed(5)}, 경도 ${p.lng.toFixed(5)}`}
inputMap.on('click',e=>setPoint(e.latlng));marker.on('dragend',e=>setPoint(e.target.getLatLng()));document.querySelector('#time').value=new Date().toISOString().slice(0,16);
const direction=d=>['북','북동','동','남동','남','남서','서','북서'][Math.round(d/45)%8];
const vector=(heading,speed)=>({x:Math.sin(heading*Math.PI/180)*speed,y:Math.cos(heading*Math.PI/180)*speed});
function destination(lat,lng,heading,km){const r=Math.PI/180,d=km/6371,b=heading*r,p=lat*r,l=lng*r,p2=Math.asin(Math.sin(p)*Math.cos(d)+Math.cos(p)*Math.sin(d)*Math.cos(b));return[p2/r,(l+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(p),Math.cos(d)-Math.sin(p)*Math.sin(p2)))/r]}
async function buoyObservation(time){const response=await fetch('data/buoy-observations.csv');if(!response.ok)throw Error();const lines=(await response.text()).trim().split(/\r?\n/),headers=lines.shift().split(','),wanted=new Date(time).getTime(),rows=lines.map(line=>Object.fromEntries(headers.map((header,index)=>[header,line.split(',')[index]])));return rows.sort((a,b)=>Math.abs(new Date(a.time)-wanted)-Math.abs(new Date(b.time)-wanted))[0]}
async function live(time){const m=`https://marine-api.open-meteo.com/v1/marine?latitude=${point.lat}&longitude=${point.lng}&current=ocean_current_velocity,ocean_current_direction`;const[buoy,marine]=await Promise.all([buoyObservation(time),fetch(m)]);if(!marine.ok)throw Error();return{buoy,sea:(await marine.json()).current}}
document.querySelector('#form').addEventListener('submit',async e=>{e.preventDefault();const result=document.querySelector('#result'),lostAt=document.querySelector('#time').value;result.hidden=false;if(document.querySelector('#floating').value==='no'){document.querySelector('#summary').textContent='이 물체는 가라앉는 것으로 선택되었습니다. 바다 표면 표류 경로는 계산하지 않고, 마지막 위치 주변 해저 수색이 필요하다고 안내합니다.';return}document.querySelector('#summary').textContent='제공한 부이 관측 자료와 해류 데이터를 불러오는 중입니다.';try{const{buoy,sea}=await live(lostAt),mass=Number(document.querySelector('#weight').value),windSpeed=Number(buoy.wind_speed),windDirection=Number(buoy.wind_direction),waveHeight=Number(buoy.significant_wave_height),waveDirection=Number(buoy.wave_direction),hours=Math.max(1,Math.min(24,(Date.now()-new Date(lostAt))/36e5)),resistance=1/(1+mass*.25),cv=vector(sea.ocean_current_direction||0,(sea.ocean_current_velocity||0)*(.6+.4*resistance)),wv=vector((windDirection+180)%360,windSpeed*3.6*.04*resistance),pv=vector((waveDirection+180)%360,waveHeight*.18*resistance),drift={x:cv.x+wv.x+pv.x,y:cv.y+wv.y+pv.y},heading=(Math.atan2(drift.x,drift.y)*180/Math.PI+360)%360,km=Math.max(.15,Math.min(8,Math.hypot(drift.x,drift.y)*hours)),end=destination(point.lat,point.lng,heading,km);document.querySelector('#summary').textContent=`부이 ${buoy.station}의 ${buoy.time.replace('T',' ')} 관측값을 반영했습니다. 해류와 ${direction(windDirection)}풍, ${direction(waveDirection)}쪽에서 오는 파도의 영향으로 ${direction(heading)}쪽 약 ${km.toFixed(2)}km 표류할 가능성이 있습니다.`;document.querySelector('#wind').textContent=`${direction(windDirection)}풍 ${windSpeed.toFixed(1)}m/s`;document.querySelector('#current').textContent=`${direction(sea.ocean_current_direction)}쪽 ${sea.ocean_current_velocity.toFixed(1)}km/h`;document.querySelector('#wave').textContent=`${direction(waveDirection)}쪽 파도 ${waveHeight.toFixed(1)}m`;if(window.rmap)window.rmap.remove();window.rmap=L.map('result-map').setView(end,13);L.tileLayer(tiles,{attribution:'&copy; OpenStreetMap'}).addTo(window.rmap);L.polyline([[point.lat,point.lng],end],{color:'#087fae',weight:5,dashArray:'8 9'}).addTo(window.rmap);L.marker([point.lat,point.lng]).addTo(window.rmap).bindPopup('분실 위치');L.marker(end).addTo(window.rmap).bindPopup('예상 위치').openPopup();window.rmap.fitBounds([[point.lat,point.lng],end],{padding:[35,35]})}catch{document.querySelector('#summary').textContent='부이 관측 자료 또는 해류 데이터를 불러오지 못했습니다. 인터넷 연결 후 다시 시도해 주세요.'}});
